### ISSUE TITLE
Update commonalities glossary with deviceLocation-subproject relevant terms 

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/DeviceLocation#12]
https://github.com/camaraproject/WorkingGroups/pull/120

**Comment by jlurien** [comment]
## Version 0.1.0 properties

- Proposed alternatives follow the [guideline in commonalities](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md#42-inputoutput-resource-definition) to name properties in snake_case.

The following is the list of properties used in the current version of the API. Almost all of them should be renamed to more descriptive and dev friendly terms, and to comply with the guidelines. Before adding terms to the global Glossary, it would be good to have some internal consensus about the alternative names.

In bold are my personal preferences.

### Terms shared with other APIs

I copy here the proposals made already in [QoD](https://github.com/camaraproject/QualityOnDemand/issues/90). In the end we will have to be aligned with commonalities glossary.

| Current term | Proposed alternatives | Comment |
|---|---|---|
| `ueId` | **`device_info`**, `device`, `user_device`, `device_id` | It should be added in description that it refers to client or user device, if not included in the name property. If it is an object with several details instead of a single unique ID, as it is now, maybe `_id` is not very accurate.  |
| `msisdn` | **`phone_number`**, `mobile_number` | MSISDN is really restricted to mobile phone numbers, but phone number is more generic. While MSISDN is very common in Telco industry it may not be friendly to general devs |
| `ipv4Addr` | **`ip_v4_address`** | At some moment we may think in consolidating both V4 and V6 formats in one single property `ip_address` as version can be deducted from value |
| `ipv6Addr` | **`ip_v6_address`** | |
| `externalId` | **`external_id`** | Description should be enhanced to inform about this option. Pending on discussions in commonalities around adoption of 3GPP GPSI |  
| `uePort`| **`device_port`**, `client_port` | uePort used for device identification in NAT scenarios should be consolidated within device info object |

### Device Location specific terms

| Current term | Proposed alternatives | Comment |
|---|---|---|
| `latitude` | **`latitude`** | Keep as it is |
| `longitude` | **`longitude`** | Keep as it is |
| `accuracy` | **`accuracy`** | Keep as it is |
| `verificationResult`| **`location_verified`** | As value is a boolean, it matches better with an adjective. In future versions we may need to enhance current response model to give mor information about the verification process, for example to deal with partial matches. | 

I would like to have some internal feedback prior to take these terms to the global glossary.

**Comment by rartych** [comment]
In order to integrate the common glossary in Commonalities it is needed to provide the first version of subproject relevant terms by ** 15th of March**.
Depending on the evolution of Area definition - currently `accuracy` means **`radius`** for Circle area shape.

**Comment by jlurien** [comment]
There is a PR #29 to define the new Area model, latest proposal is `accuracy` instead of radius.

**Comment by shilpa-padgaonkar** [comment]
Thank you for your contribution to the commonalities glossary https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md
