### ISSUE TITLE
Name for new API for subscription events to location verification

### ISSUE THREAD

**Issue by jlurien** [camaraproject/DeviceLocation#69]
As agreed for #18, we should move the new API proposal in [PR #49](https://github.com/camaraproject/DeviceLocation/pull/49) to a new API spec. Which name do you prefer:

- `geofencing`
- `location-verification-subscription`
- Other, please suggest

**Comment by bigludo7** [comment]
From Orange we have a slight preference for `location-verification-subscription` as it is more consistent with the 2 other APIs

Thanks

**Comment by JoachimDahlgren** [comment]
The original description of the purpose of this new API that reads "So that developers are informed if a device is leaving or entering the "radius". This is important for tracking devices for Presetting of Homesettings or for tracking of logistics and more". 

This aligns with how geofencing is usually described. Using the term geofencing would also be beneficial in case we later want to expand the API to handle multiple devices or even any device moving into or out of an area.

**Comment by alpaycetin74** [comment]
I tend to think geofencing is a better representation of what this api does.

**Comment by jlurien** [comment]
For TEF, `geofencing` is also acceptable.

**Comment by akoshunyadi** [comment]
From DT side we can also accept geofencing. Althought we think that not use case specific names are generally better, but in this case the API is specific and the long name would  just confuse API users.
